### ISSUE TITLE
Plugin added to hoobs, but configurator is not working

### ISSUE THREAD

**Issue by acidkill** [robinjhector/homebridge-tibber-price#10]
Hi. I asked guys from Hoobs to add your plugin and they did it, but saddly - configurator doesn't work there and your readme doesn't have a config example. Was reading code a while, but hard to guess f.ex. accessory names without sample config.

Trying to config it in config file mode.

**Logs:**
```
28/09/2022, 00:32:02Tibber Price BridgeLoaded plugin 'homebridge-tibber-price'
28/09/2022, 00:32:02Tibber Price BridgeLoading 1 platform...
28/09/2022, 00:32:02Tibber Price BridgeWARNINGunhandled rejection: Error: (homebridge-tibber-price) Invalid config! "accessToken" is required
```

**Plugin Config:**

```json
{
    "platform": "homebridge-tibber-price",
    "accessToken": "lajnfgawlifguhnqwligfubnqweiolgfbqweig"
}
```

**Screenshots:**
![Screenshot 2022-09-28 at 00 45 18](https://user-images.githubusercontent.com/58035493/192651073-535578cd-fc79-4b2d-9d22-6a164f8c38e6.png)
![Screenshot 2022-09-28 at 00 51 38](https://user-images.githubusercontent.com/58035493/192651468-40ad6a99-e014-42b2-9824-fa4c3f0ae989.png)

**Environment:**

* **Plugin Version**: 1.0.1
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.17.1
* **NPM Version**: 8.15.0
* **Operating System**: Hoobs 4.2.8 (rapberry version of bullseye)

**Comment by robinjhector** [comment]
Hi! Thanks for creating this question 👍 
I'm not familiar with Hoobs, but I think we can get this working.

Basically the [config.schema.json](https://github.com/robinjhector/homebridge-tibber-price/blob/master/config.schema.json) should outline the properties required and needed 👍 

But here's my own configuration (taken from my homebridge config.json):

```json
{
  "accessToken": "<redacted>",
  "priceIncTax": true,
  "activatePriceGraphing": true,
  "activatePriceSensor": true,
  "activateRelativePriceSensor": true,
  "platform": "HomebridgeTibberPrice",
  "_bridge": {
    "username": "<redacted>",
    "port": 57508
  }
}
```

One thing that stands out is the difference between my `platform` property, and yours

**Comment by robinjhector** [comment]
I can add something to the readme about this :)

**Comment by acidkill** [comment]
Thank you very much for the help and your great work!
Got it working.

Pasting my working Hoobs config here (it worked also with relative price, but I will not be using it):

```
{
    "accessories": [],
    "platforms": [
        {
            "platform": "HomebridgeTibberPrice",
            "accessToken": "<redacted>",
            "priceIncTax": true,
            "activatePriceGraphing": true,
            "activatePriceSensor": true,
            "activateRelativePriceSensor": false
        }
    ]
}
```
Below attached log showing everything works as intended.

```
28/09/2022, 20:01:12Tibber Price Bridge starting
28/09/2022, 20:01:16Tibber Price BridgeLoaded plugin 'homebridge-tibber-price'
28/09/2022, 20:01:16Tibber Price BridgeLoading 1 platforms...
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceInitialized Tibber client
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceConfiguring accessory Electricity price, with id cb7128bb-3988-4514-9542-01fcb1299331
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceConfiguring accessory Relative electricity price, with id d6140a59-bd4b-435e-a3a5-d3200b2e93f0
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceRegistering devices...
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceRegistering price sensor with id cb7128bb-3988-4514-9542-01fcb1299331
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceRemoving relative price sensor with id d6140a59-bd4b-435e-a3a5-d3200b2e93f0
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceWill produce a chart PNG, stored at: /var/lib/hoobs/tibberpricebridge/tibber-price/price-chart.png
28/09/2022, 20:01:16Tibber Price BridgeHomebridgeTibberPriceStarting background tasks...
28/09/2022, 20:01:16Tibber Price BridgeBridge is running on port 57508.
```

**Comment by Mebbz** [comment]
Hi @robinjhector,

This plugin looks awesome, but unfortunately it seems like I'm experiencing the same issue as @acidkill. I'm on the exact same hw setup and sw versions as acidkill, so it's very strange I'm unable to replicate his success using the config he pasted above (with my own access token of course).

When I install the plugin the bridge becomes unresponsive and unable to start:
![Skjermbilde 2022-10-12 kl  15 01 42](https://user-images.githubusercontent.com/107172313/195351530-6a08ecaf-477c-4b01-883f-99b091b0e08f.png)


And whatever I try I end up getting the access token error:

**TibberWARNINGunhandled rejection: Error: (homebridge-tibber-price) Invalid config! "accessToken" is required**

I know you're not familiar with Hoobs, but any ideas? @acidkill, anything else you did with the config other than what you pasted above?

Thanks in advance! :)

**Comment by acidkill** [comment]
Are you adding that in Tibber Price config or Advanced -> Tibber Price Bridge?
Works only with the second one.

**Comment by acidkill** [comment]
It needs to be added here.
![Screenshot 2022-10-12 at 17 51 02](https://user-images.githubusercontent.com/58035493/195389874-defaa6d8-a182-484c-a232-b5e7f984498b.png)
In "normal config" just leave like that:
![Screenshot 2022-10-12 at 17 52 08](https://user-images.githubusercontent.com/58035493/195390131-08aaa36a-e591-4756-9ad4-f7142b0902ab.png)

**Comment by Mebbz** [comment]
@acidkill, thanks a lot! Works like a charm now :)

**Comment by robinjhector** [comment]
Thanks for helping out @acidkill ! 🥇
