### ISSUE TITLE
No values

### ISSUE THREAD

**Issue by FluGanz** [robinjhector/homebridge-tibber-price#36]
**Describe The Bug:**
I get no values in % or lux

**Plugin Config:**

 "accessToken": "token",
            "priceIncTax": true,
            "activatePriceGraphing": true,
            "activatePriceSensor": true,
            "activateRelativePriceSensor": true,
            "_bridge": {
                "username": "0E:E2:F6:50:58:B6",
                "port": 57342
            },
            "platform": "HomebridgeTibberPrice"

**Screenshots:**

![96D7AD45-9178-4E91-BDA3-1CA9D78D5F75](https://user-images.githubusercontent.com/77684722/204348375-c86f1e29-8ce8-46af-8798-d8f26b0a3bfb.png)

**Comment by robinjhector** [comment]
Hmm could be the same issue as #29 , do you have any logs from the plugin to verify?
I'll try and make the error handling a bit more robust!

**Comment by robinjhector** [comment]
Hi @FluGanz ! I've made the error handling a bit more robust.
Try updating to 1.0.3 and see if that fixes the problem.
If not, please provide some logs from homebridge 👍 

Closing for now
